// ════════════════════════════════════════════════════════════════════════════
// CENTRAL-UI-PARITY R6F — Aufgaben und Dokumente vom zweiten Rechner: Aufgabe anlegen, Aufgabe ändern
// (inkl. „erledigt"), Dokument hochladen, Text eines Dokuments erkennen.
//
// Derselbe Bau wie bei den Angeboten (`offer-commands.ts`):
//
//  1. **Keine zweite Logik.** Jeder Befehl ruft die Hausfolge, die auch die Maske des Primary ruft
//     (`office/task-house.ts`, `office/document-house.ts`) — in der Transaktion des Auftrags.
//  2. **Der Rumpf ist ein Wunsch.** Kennung, Filiale, Benutzer (auch `created_by`/`actor`),
//     Zeitstempel, Fassung und alles, was der Primary bestimmt (Zeitpunkt des Erledigens, „automatisch",
//     Typ und Größe einer Datei, ihr Speicherort, JEDES Ergebnis der Texterkennung), stehen namentlich
//     auf der Verbotsliste; ein unbekanntes Feld wird abgewiesen statt ignoriert. Der Status ist nur
//     beim Ändern einer Aufgabe ein Wunsch — und dort nur einer aus dem Vokabular der Maske.
//  3. **Ändern braucht die gesehene Fassung.** `tasks.update` und `documents.set_ocr` nennen
//     `expectedRevision`; verglichen wird INNERHALB der Transaktion. Anlegen braucht keine.
//  4. **Texterkennung: der Primary rechnet.** `documents.set_ocr` nennt nur Dokument und Fassung; der
//     Primary erkennt den Text aus dem Inhalt SEINER Datenbank. Scheitert die Erkennung selbst, ist
//     das kein Urteil (nichts wird festgehalten, dieselbe Kennung darf es erneut versuchen); eine
//     Wiederholung nach einem Erfolg rechnet nicht noch einmal, sondern bekommt die eingefrorene Antwort.
//
// Bewusst NICHT dabei: Löschen einer Aufgabe / eines Dokuments und das Umhängen eines Dokuments —
// das bleibt am Primary (`primaryOnlyDeleteProps`).
// ════════════════════════════════════════════════════════════════════════════
import { getDatabase, saveDatabaseDurably } from '@/core/db/database';
import {
  beginLedgerTransaction, commitLedgerTransaction, rollbackLedgerTransaction,
} from '@/core/ledger/posting';
import { CommandNotEvaluated, CommandRejected, runRemoteCommand, type CommandOutcome, type EngineDeps } from './mutation-engine';
import type { CommandIdentity } from './command-ledger';
import { BusinessError, registerCommand, type CommandActor } from './command-registry';
import { assertHouseBranch } from './remote-create-support';
import { OfficeRejected, type OfficeCtx } from '@/core/office/office-rules';
import {
  createTaskInHouse, taskCreateInput, taskUpdateInput, updateTaskInHouse,
  type TaskCreateInput, type TaskUpdateInput,
} from '@/core/office/task-house';
import {
  OcrEngineFailed, defaultOcrEngine, documentOcrInput, documentUploadInput, setDocumentOcrInHouse, uploadDocumentInHouse,
  type DocumentOcrInput, type DocumentUploadInput, type OcrEngine,
} from '@/core/office/document-house';

export const OP_TASKS_CREATE = 'tasks.create';
export const OP_TASKS_UPDATE = 'tasks.update';
export const OP_DOCUMENTS_UPLOAD = 'documents.upload';
export const OP_DOCUMENTS_SET_OCR = 'documents.set_ocr';

export const OFFICE_OPS = [OP_TASKS_CREATE, OP_TASKS_UPDATE, OP_DOCUMENTS_UPLOAD, OP_DOCUMENTS_SET_OCR] as const;

/** Ein unbrauchbarer Rumpf — eine Antwort, keine Störung. Der Client korrigiert und schickt neu. */
export class OfficePayloadError extends Error {
  readonly code: string;
  constructor(message: string, code = 'OFFICE_PAYLOAD_INVALID') {
    super(message);
    this.name = 'OfficePayloadError';
    this.code = code;
  }
}

/** Was der Client nie setzt: wer, wo, wann, welche Kennung, welche Fassung, welcher Zustand. */
const FORBIDDEN = [
  'id', 'branchId', 'branch_id', 'tenantId', 'userId', 'createdBy', 'created_by', 'actor',
  'createdAt', 'created_at', 'updatedAt', 'revision', 'status',
];
/** Was der Primary selbst bestimmt — je Befehl. */
export const OFFICE_COMPUTED = {
  task: ['completedAt', 'completed_at', 'autoGenerated', 'auto_generated', 'version', 'syncStatus'],
  document: ['filePath', 'file_path', 'fileType', 'file_type', 'fileSize', 'file_size', 'mime', 'size', 'documentId',
    'ocrText', 'ocrConfidence', 'ocrReviewed', 'extractedFields', 'aiSuggestions', 'thumbnailPath', 'version', 'syncStatus'],
  ocr: ['text', 'ocrText', 'ocr_text', 'confidence', 'ocrConfidence', 'ocr_confidence', 'ocrReviewed', 'ocr_reviewed',
    'reviewed', 'result', 'extractedFields', 'aiSuggestions', 'completedAt', 'ocrAt', 'content', 'filePath', 'fileType'],
} as const;

const TASK_FIELDS = ['title', 'description', 'type', 'priority', 'dueAt', 'linkedEntityType', 'linkedEntityId', 'assignedTo'];

const isPlain = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

function strict(raw: unknown, allowed: readonly string[], computed: readonly string[], forbidden: readonly string[] = FORBIDDEN): Record<string, unknown> {
  if (!isPlain(raw)) throw new OfficePayloadError('payload must be an object');
  for (const k of Object.keys(raw)) {
    if (forbidden.includes(k) || computed.includes(k)) throw new OfficePayloadError(`the primary decides ${k}, not the client`);
    if (!allowed.includes(k)) throw new OfficePayloadError(`unknown field: ${k}`);
  }
  return raw;
}

/** Die Eingaberegel als Prüfung des Rumpfs: ihr Nein kommt mit IHREM Code zurück — derselbe wie am Primary. */
function rule<T>(fn: () => T): T {
  try { return fn(); } catch (e) {
    if (e instanceof OfficeRejected) throw new OfficePayloadError(e.message, e.code);
    throw e;
  }
}

/** Dieselbe Folge INNERHALB des Auftrags: dort ist ihr Nein ein eingefrorenes Urteil. */
function urteil<T>(fn: () => T): T {
  try { return fn(); } catch (e) {
    if (e instanceof OfficeRejected) throw new CommandRejected(e.code, e.message);
    throw e;
  }
}

function revisionOf(v: unknown, what: string): number {
  if (typeof v !== 'number' || !Number.isInteger(v) || v < 1) {
    throw new OfficePayloadError(`expectedRevision is required — a change to a ${what} must say which revision it saw`);
  }
  return v;
}

/** Im Namen des geprüften Absenders — nie der Anmeldung des Primary. */
const ctxOf = (identity: CommandIdentity): OfficeCtx => ({ branchId: identity.branchId, userId: identity.userId });

// ── Die Rümpfe ──────────────────────────────────────────────────────────────

export function parseTaskCreate(raw: unknown): TaskCreateInput {
  const r = strict(raw, TASK_FIELDS, OFFICE_COMPUTED.task);
  return rule(() => taskCreateInput(r));
}

export function parseTaskUpdate(raw: unknown): TaskUpdateInput & { expectedRevision: number } {
  // Hier ist der Status ein Wunsch — geprüft gegen das Vokabular der Maske, der Übergang im Haus.
  const r = strict(raw, ['taskId', 'expectedRevision', 'status', ...TASK_FIELDS], OFFICE_COMPUTED.task,
    FORBIDDEN.filter((k) => k !== 'status'));
  const expectedRevision = revisionOf(r.expectedRevision, 'task');
  return { ...rule(() => taskUpdateInput(r)), expectedRevision };
}

export function parseDocumentUpload(raw: unknown): DocumentUploadInput {
  const r = strict(raw, ['fileName', 'content', 'docClass', 'linkedEntityType', 'linkedEntityId'], OFFICE_COMPUTED.document);
  return rule(() => documentUploadInput(r));
}

export function parseDocumentOcr(raw: unknown): DocumentOcrInput & { expectedRevision: number } {
  const r = strict(raw, ['documentId', 'expectedRevision'], OFFICE_COMPUTED.ocr);
  const expectedRevision = revisionOf(r.expectedRevision, 'document');
  return { ...rule(() => documentOcrInput(r)), expectedRevision };
}

// ── Die Läufe ───────────────────────────────────────────────────────────────

export function officeDeps(): EngineDeps {
  return {
    db: getDatabase() as never,
    begin: beginLedgerTransaction,
    commit: commitLedgerTransaction,
    rollback: rollbackLedgerTransaction,
    durableSave: saveDatabaseDurably,
    now: () => new Date().toISOString(),
  };
}

export function runTaskCreate(deps: EngineDeps, identity: CommandIdentity, raw: unknown): Promise<CommandOutcome> {
  const input = parseTaskCreate(raw);
  return runRemoteCommand(deps, identity, () => {
    assertHouseBranch(identity);
    const r = urteil(() => createTaskInHouse(input, ctxOf(identity)));
    return { taskId: r.taskId, revision: r.revision };
  });
}

export function runTaskUpdate(deps: EngineDeps, identity: CommandIdentity, raw: unknown): Promise<CommandOutcome> {
  const input = parseTaskUpdate(raw);
  return runRemoteCommand(deps, identity, () => {
    assertHouseBranch(identity);
    const r = urteil(() => updateTaskInHouse(input, ctxOf(identity)));
    return { taskId: r.taskId, revision: r.revision, status: r.status, changed: r.changed };
  });
}

export function runDocumentUpload(deps: EngineDeps, identity: CommandIdentity, raw: unknown): Promise<CommandOutcome> {
  const input = parseDocumentUpload(raw);
  return runRemoteCommand(deps, identity, () => {
    assertHouseBranch(identity);
    const r = urteil(() => uploadDocumentInHouse(input, ctxOf(identity)));
    // Klein: nie der Inhalt — der kommt über `documents.content.get`, wenn jemand ihn öffnet.
    return { documentId: r.documentId, revision: r.revision, fileSize: r.fileSize, fileType: r.fileType };
  });
}

export function runDocumentOcr(
  deps: EngineDeps, identity: CommandIdentity, raw: unknown, engine: OcrEngine = defaultOcrEngine,
): Promise<CommandOutcome> {
  const input = parseDocumentOcr(raw);
  return runRemoteCommand(deps, identity, async () => {
    assertHouseBranch(identity);
    let r;
    try {
      r = await setDocumentOcrInHouse(input, ctxOf(identity), engine);
    } catch (e) {
      if (e instanceof OfficeRejected) throw new CommandRejected(e.code, e.message);
      // Die Erkennung selbst scheiterte: kein Urteil über das Dokument — nichts festhalten.
      if (e instanceof OcrEngineFailed) throw new CommandNotEvaluated(e.code, e.message);
      throw e;
    }
    return { documentId: r.documentId, revision: r.revision, text: r.text, confidence: r.confidence, stored: r.stored };
  });
}

// ── Die Anmeldung ─────────────────────────────────────────────────────────

type Run = (deps: EngineDeps, identity: CommandIdentity, raw: unknown) => Promise<CommandOutcome>;

async function execute(run: Run, op: string, payload: unknown, actor?: CommandActor): Promise<Record<string, unknown>> {
  if (!actor) throw new Error(`${op} needs an authenticated identity`);
  const body = (payload as { input?: unknown } | null)?.input ?? payload;
  let outcome: CommandOutcome;
  try {
    outcome = await run(officeDeps(), { ...actor, op }, body);
  } catch (err) {
    // Ein unbrauchbarer Rumpf ist eine Antwort: neu schicken mit einer NEUEN Kennung.
    if (err instanceof OfficePayloadError) throw new BusinessError(err.code, err.message);
    throw err;
  }
  if (outcome.kind === 'rejected') {
    // Nur ein EINGEFRORENES Urteil ist ein fachliches Nein; alles andere ist ein offener Ausgang.
    if (!outcome.frozen) throw new CommandNotEvaluated(outcome.code, outcome.message);
    throw new BusinessError(outcome.code, outcome.message);
  }
  return { ...(outcome.value as Record<string, unknown>), replayed: outcome.replayed };
}

registerCommand(OP_TASKS_CREATE, { kind: 'mutation', handler: (p, a) => execute(runTaskCreate, OP_TASKS_CREATE, p, a) });
registerCommand(OP_TASKS_UPDATE, { kind: 'mutation', handler: (p, a) => execute(runTaskUpdate, OP_TASKS_UPDATE, p, a) });
registerCommand(OP_DOCUMENTS_UPLOAD, { kind: 'mutation', handler: (p, a) => execute(runDocumentUpload, OP_DOCUMENTS_UPLOAD, p, a) });
registerCommand(OP_DOCUMENTS_SET_OCR, { kind: 'mutation', handler: (p, a) => execute(runDocumentOcr, OP_DOCUMENTS_SET_OCR, p, a) });
