// Plan §Automation §2 — Daily Sweep.
// Beim App-Start + alle 6h: abgelaufene Datensätze automatisch auf 'expired' setzen,
// überfällige Forderungen als Reminder-Tasks anlegen.
import { v4 as uuid } from 'uuid';
import { getDatabase, saveDatabase } from '@/core/db/database';
import { query, currentBranchId } from '@/core/db/helpers';
import { eventBus } from '@/core/events/event-bus';
import { trackInsert, trackStatusChange } from '@/core/sync/track';

function today(): string {
  return new Date().toISOString().split('T')[0];
}

function createAutoTask(params: {
  branchId: string;
  title: string;
  description?: string;
  type: 'consignment_expiry' | 'payment_reminder' | 'agent_return' | 'order_delivery' | 'repair_ready';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  linkedEntityType: 'customer' | 'consignment' | 'debt' | 'agent_transfer' | 'order' | 'repair' | 'invoice';
  linkedEntityId: string;
  dueAt?: string;
}): void {
  // Deduplizieren: wenn bereits eine offene Task gleicher Art für dasselbe Entity existiert → skip.
  const existing = query(
    `SELECT id FROM tasks
       WHERE branch_id = ? AND linked_entity_type = ? AND linked_entity_id = ?
         AND type = ? AND status != 'completed' AND status != 'cancelled'`,
    [params.branchId, params.linkedEntityType, params.linkedEntityId, params.type]
  );
  if (existing.length > 0) return;

  const db = getDatabase();
  const now = new Date().toISOString();
  const id = uuid();
  db.run(
    `INSERT INTO tasks (id, branch_id, title, description, type, priority, due_at,
       linked_entity_type, linked_entity_id, status, auto_generated, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'open', 1, ?)`,
    [id, params.branchId, params.title, params.description || null, params.type,
     params.priority, params.dueAt || null, params.linkedEntityType, params.linkedEntityId, now]
  );
  trackInsert('tasks', id, { autoGenerated: true, type: params.type });
}

export function runDailySweep(): void {
  try {
    const db = getDatabase();
    const now = new Date().toISOString();
    const tday = today();
    let branchId: string;
    try { branchId = currentBranchId(); } catch { return; } // Nicht eingeloggt

    let changed = 0;

    // 1. Expired Offers — valid_until < heute + status in sent/viewed → expired
    const expOffers = query(
      `SELECT id FROM offers WHERE branch_id = ? AND valid_until IS NOT NULL AND valid_until < ?
         AND status IN ('sent', 'viewed', 'draft')`,
      [branchId, tday]
    );
    for (const row of expOffers) {
      const oid = row.id as string;
      db.run(`UPDATE offers SET status = 'expired', updated_at = ? WHERE id = ?`, [now, oid]);
      trackStatusChange('offers', oid, 'sent/viewed/draft', 'expired');
      eventBus.emit('offer.expired', 'offer', oid, { auto: true });
      changed++;
    }

    // 2. Expired Consignments — expiry_date < heute + status active → expired + Task
    const expCons = query(
      `SELECT id, product_id FROM consignments WHERE branch_id = ? AND expiry_date IS NOT NULL AND expiry_date < ?
         AND status = 'active'`,
      [branchId, tday]
    );
    for (const row of expCons) {
      const cid = row.id as string;
      db.run(`UPDATE consignments SET status = 'expired', updated_at = ? WHERE id = ?`, [now, cid]);
      trackStatusChange('consignments', cid, 'active', 'expired');
      createAutoTask({
        branchId,
        title: 'Consignment abgelaufen',
        description: 'Das Consignment ist abgelaufen — Rücksprache mit Owner oder verlängern.',
        type: 'consignment_expiry',
        priority: 'high',
        linkedEntityType: 'consignment',
        linkedEntityId: cid,
      });
      changed++;
    }

    // 3. Overdue Debts — due_date < heute + status OPEN/PARTIAL → Reminder-Task
    const overdueDebts = query(
      `SELECT id, counterparty, customer_id, amount, paid_amount, direction FROM debts
         WHERE branch_id = ? AND due_date IS NOT NULL AND due_date < ?
           AND status IN ('OPEN', 'PARTIALLY_REPAID')`,
      [branchId, tday]
    );
    for (const row of overdueDebts) {
      const did = row.id as string;
      const dir = row.direction as string;
      const who = row.counterparty as string;
      const custId = (row.customer_id as string | null) || null;
      const amount = (row.amount as number) || 0;
      const paid = (row.paid_amount as number) || 0;
      const open = Math.max(0, amount - paid);
      const titleStem = dir === 'OWED_TO_US' ? 'Überfällige Forderung' : 'Überfällige Verbindlichkeit';
      // Verknüpfung mit Customer wenn vorhanden, sonst ohne Linked-Entity (erscheint trotzdem in Tasks-Liste).
      if (custId) {
        createAutoTask({
          branchId,
          title: `${titleStem}: ${who}`,
          description: `${open.toFixed(2)} BHD offen seit über dem Fälligkeitsdatum (Debt ID: ${did.slice(0, 8)}).`,
          type: 'payment_reminder',
          priority: 'high',
          linkedEntityType: 'customer',
          linkedEntityId: custId,
        });
      } else {
        // Fallback: Dedup via Titel-Check
        const existing = query(
          `SELECT id FROM tasks WHERE branch_id = ? AND title = ? AND status NOT IN ('completed', 'cancelled')`,
          [branchId, `${titleStem}: ${who}`]
        );
        if (existing.length === 0) {
          const tid = uuid();
          db.run(
            `INSERT INTO tasks (id, branch_id, title, description, type, priority,
               status, auto_generated, created_at)
             VALUES (?, ?, ?, ?, 'payment_reminder', 'high', 'open', 1, ?)`,
            [tid, branchId, `${titleStem}: ${who}`,
             `${open.toFixed(2)} BHD offen seit über dem Fälligkeitsdatum (Debt ID: ${did.slice(0, 8)}).`, now]
          );
          trackInsert('tasks', tid, { autoGenerated: true, debtId: did });
        }
      }
      changed++;
    }

    if (changed > 0) {
      saveDatabase();
      console.log(`[DailySweep] ${changed} Datensätze aktualisiert/Tasks erzeugt.`);
    }
  } catch (err) {
    console.warn('[DailySweep] failed', err);
  }
}
