// ═══════════════════════════════════════════════════════════
// LATAIF — Task Store (Zustand)
// Branch-aware task management
// ═══════════════════════════════════════════════════════════

import { create } from 'zustand';
import type { Task, TaskType, TaskPriority, TaskStatus, LinkedEntityType } from '@/core/models/types';
import { getDatabase, saveDatabase } from '@/core/db/database';
import { query } from '@/core/db/helpers';
import { trackDelete } from '@/core/sync/track';
// CENTRAL-UI-PARITY — auf einem Rechner ohne Datenbank holt derselbe Aufruf den Stand vom Primary.
import { hydrateFromPrimary } from '@/core/data/primary-source';
// CENTRAL-UI-PARITY R1 — der Ausweis der Leseanfrage reist als Parameter, nicht als globaler
// Zustand: am Primary aus der eigenen Sitzung, aus der Ferne aus dem geprueften Absender.
import { localReadContext, type BusinessReadContext } from '@/core/data/read-context';
// CENTRAL-UI-PARITY R6F — Anlegen und Aendern (inkl. „erledigt") laufen durch EINE Hausfolge, am
// Primary wie fuer PC2 (`tasks.create`/`tasks.update`). Kein eigenes SQL mehr hier.
import { runOnPrimary } from '@/core/data/primary-action';
import { localOfficeCtx, officeActionSync } from '@/core/office/office-rules';
import {
  assertTasksHere, createTaskInHouse, updateTaskInHouse,
  type TaskCreateInput, type TaskCreated, type TaskUpdateInput, type TaskUpdated,
} from '@/core/office/task-house';

interface CreateTaskData {
  title: string;
  description?: string;
  type?: TaskType;
  priority?: TaskPriority;
  dueAt?: string;
  linkedEntityType?: LinkedEntityType;
  linkedEntityId?: string;
  assignedTo?: string;
  notes?: string;
}

interface UpdateTaskData {
  title?: string;
  description?: string;
  type?: TaskType;
  priority?: TaskPriority;
  dueAt?: string;
  linkedEntityType?: LinkedEntityType;
  linkedEntityId?: string;
  assignedTo?: string;
  notes?: string;
  status?: TaskStatus;
}

/** R6F — eine Aufgabe mit ihrer Fassung: wer sie ändert, nennt, welchen Stand er gesehen hat. */
export type TaskRow = Task & { revision: number };

interface TaskStore {
  tasks: TaskRow[];
  loading: boolean;
  loadTasks: () => void;
  createTask: (data: CreateTaskData) => TaskRow;
  updateTask: (id: string, data: UpdateTaskData) => void;
  completeTask: (id: string) => void;
  deleteTask: (id: string) => void;
  getTasksForEntity: (entityType: LinkedEntityType, entityId: string) => TaskRow[];
}

function rowToTask(row: Record<string, unknown>): TaskRow {
  return {
    id: row.id as string,
    title: row.title as string,
    description: row.description as string | undefined,
    type: (row.type as TaskType) || 'general',
    priority: (row.priority as TaskPriority) || 'medium',
    dueAt: row.due_at as string | undefined,
    linkedEntityType: row.linked_entity_type as LinkedEntityType | undefined,
    linkedEntityId: row.linked_entity_id as string | undefined,
    assignedTo: row.assigned_to as string | undefined,
    notes: (row.notes as string | null) ?? undefined,
    status: (row.status as TaskStatus) || 'open',
    autoGenerated: row.auto_generated === 1,
    createdAt: row.created_at as string,
    completedAt: row.completed_at as string | undefined,
    revision: Number(row.revision ?? 0),
  };
}

function taskById(id: string): TaskRow {
  return rowToTask(query('SELECT * FROM tasks WHERE id = ?', [id])[0] ?? { id });
}

export const useTaskStore = create<TaskStore>((set, get) => ({
  tasks: [],
  loading: false,

  loadTasks: () => {
    if (hydrateFromPrimary('store.tasks.get', (d) => set(d as never))) return;
    try {
      set({ ...loadTasksFor(localReadContext()), loading: false });
    } catch {
      set({ tasks: [], loading: false });
    }
  },

  // R6F — die alten, synchronen Store-Aufrufe rufen dieselbe Hausfolge wie die Maske (in einer
  // eigenen Klammer). R7A: `notes` hat seine Spalte und wird gespeichert.
  createTask: (data) => {
    const r = officeActionSync(assertTasksHere, (ctx) => createTaskInHouse({
      title: data.title,
      description: data.description ?? null,
      type: data.type,
      priority: data.priority,
      dueAt: data.dueAt ?? null,
      linkedEntityType: data.linkedEntityType ?? null,
      linkedEntityId: data.linkedEntityId ?? null,
      assignedTo: data.assignedTo ?? null,
      notes: data.notes ?? null,
    }, ctx));
    saveDatabase();
    get().loadTasks();
    return taskById(r.taskId);
  },

  updateTask: (id, data) => {
    // Wie bisher: ein genanntes, aber leeres Feld heisst „leeren" (`val ?? null`).
    const input: Record<string, unknown> = { taskId: id };
    for (const [key, val] of Object.entries(data)) input[key] = val ?? null;
    officeActionSync(assertTasksHere, (ctx) => updateTaskInHouse(input as unknown as TaskUpdateInput, ctx));
    saveDatabase();
    get().loadTasks();
  },

  completeTask: (id) => {
    officeActionSync(assertTasksHere, (ctx) => updateTaskInHouse({ taskId: id, status: 'completed' }, ctx));
    saveDatabase();
    get().loadTasks();
  },

  deleteTask: (id) => {
    const db = getDatabase();
    db.run('DELETE FROM tasks WHERE id = ?', [id]);
    saveDatabase();
    trackDelete('tasks', id);
    get().loadTasks();
  },

  getTasksForEntity: (entityType, entityId) => {
    return get().tasks.filter(
      t => t.linkedEntityType === entityType && t.linkedEntityId === entityId
    );
  },
}));

// ── CENTRAL-UI-PARITY R6F — die Anschlüsse der Maske am Primary ─────────────
//
// Exklusiv, in EINER Transaktion, danach durabel (`runOnPrimary`) — dieselbe Klammer, die ein
// Fernauftrag von der Maschine bekommt. Ohne Geschäftsdatenbank verweigern sie, BEVOR eine
// Transaktion beginnt.

function reloadTasks(): void {
  useTaskStore.getState().loadTasks();
}

/** „Create Task" am Primary. */
export function createTaskOnPrimary(input: Record<string, unknown>): Promise<TaskCreated> {
  try { assertTasksHere(); } catch (e) { return Promise.reject(e); }
  return runOnPrimary(() => createTaskInHouse(input as unknown as TaskCreateInput, localOfficeCtx()), reloadTasks);
}

/** „Save Changes" und „Complete" am Primary. */
export function updateTaskOnPrimary(input: Record<string, unknown>): Promise<TaskUpdated> {
  try { assertTasksHere(); } catch (e) { return Promise.reject(e); }
  return runOnPrimary(() => updateTaskInHouse(input as unknown as TaskUpdateInput, localOfficeCtx()), reloadTasks);
}

/** CENTRAL-UI-PARITY R2B — die Aufgaben einer Filiale, zustandsfrei. */
export function loadTasksFor(ctx: BusinessReadContext): { tasks: TaskRow[] } {
  const rows = query(
    'SELECT * FROM tasks WHERE branch_id = ? ORDER BY CASE status WHEN \'open\' THEN 0 WHEN \'in_progress\' THEN 1 WHEN \'completed\' THEN 2 WHEN \'cancelled\' THEN 3 END, due_at ASC, created_at DESC',
    [ctx.branchId]
  );
  return { tasks: rows.map(rowToTask) };
}
