// ═══════════════════════════════════════════════════════════
// LATAIF — Task Store (Zustand)
// Branch-aware task management
// ═══════════════════════════════════════════════════════════

import { create } from 'zustand';
import { v4 as uuid } from 'uuid';
import type { Task, TaskType, TaskPriority, TaskStatus, LinkedEntityType } from '@/core/models/types';
import { getDatabase, saveDatabase } from '@/core/db/database';
import { query, currentBranchId, currentUserId } from '@/core/db/helpers';
import { eventBus } from '@/core/events/event-bus';
import { trackInsert, trackUpdate, trackDelete } from '@/core/sync/track';

interface CreateTaskData {
  title: string;
  description?: string;
  type?: TaskType;
  priority?: TaskPriority;
  dueAt?: string;
  linkedEntityType?: LinkedEntityType;
  linkedEntityId?: string;
  assignedTo?: string;
  notes?: string;
}

interface UpdateTaskData {
  title?: string;
  description?: string;
  type?: TaskType;
  priority?: TaskPriority;
  dueAt?: string;
  linkedEntityType?: LinkedEntityType;
  linkedEntityId?: string;
  assignedTo?: string;
  status?: TaskStatus;
}

interface TaskStore {
  tasks: Task[];
  loading: boolean;
  loadTasks: () => void;
  createTask: (data: CreateTaskData) => Task;
  updateTask: (id: string, data: UpdateTaskData) => void;
  completeTask: (id: string) => void;
  deleteTask: (id: string) => void;
  getTasksForEntity: (entityType: LinkedEntityType, entityId: string) => Task[];
}

function rowToTask(row: Record<string, unknown>): Task {
  return {
    id: row.id as string,
    title: row.title as string,
    description: row.description as string | undefined,
    type: (row.type as TaskType) || 'general',
    priority: (row.priority as TaskPriority) || 'medium',
    dueAt: row.due_at as string | undefined,
    linkedEntityType: row.linked_entity_type as LinkedEntityType | undefined,
    linkedEntityId: row.linked_entity_id as string | undefined,
    assignedTo: row.assigned_to as string | undefined,
    status: (row.status as TaskStatus) || 'open',
    autoGenerated: row.auto_generated === 1,
    createdAt: row.created_at as string,
    completedAt: row.completed_at as string | undefined,
  };
}

export const useTaskStore = create<TaskStore>((set, get) => ({
  tasks: [],
  loading: false,

  loadTasks: () => {
    try {
      const branchId = currentBranchId();
      const rows = query(
        'SELECT * FROM tasks WHERE branch_id = ? ORDER BY CASE status WHEN \'open\' THEN 0 WHEN \'in_progress\' THEN 1 WHEN \'completed\' THEN 2 WHEN \'cancelled\' THEN 3 END, due_at ASC, created_at DESC',
        [branchId]
      );
      set({ tasks: rows.map(rowToTask), loading: false });
    } catch {
      set({ tasks: [], loading: false });
    }
  },

  createTask: (data) => {
    const db = getDatabase();
    const now = new Date().toISOString();
    const id = uuid();

    let branchId: string;
    try { branchId = currentBranchId(); } catch { branchId = 'branch-main'; }

    let userId: string | null;
    try { userId = currentUserId(); } catch { userId = null; }

    const task: Task = {
      id,
      title: data.title,
      description: data.description,
      type: data.type || 'general',
      priority: data.priority || 'medium',
      dueAt: data.dueAt,
      linkedEntityType: data.linkedEntityType,
      linkedEntityId: data.linkedEntityId,
      assignedTo: data.assignedTo,
      status: 'open',
      autoGenerated: false,
      createdAt: now,
    };

    db.run(
      `INSERT INTO tasks (id, branch_id, title, description, type, priority, due_at, linked_entity_type, linked_entity_id, assigned_to, status, auto_generated, created_at, created_by)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'open', 0, ?, ?)`,
      [id, branchId, task.title, task.description || null, task.type, task.priority,
       task.dueAt || null, task.linkedEntityType || null, task.linkedEntityId || null,
       task.assignedTo || null, now, userId]
    );

    saveDatabase();
    trackInsert('tasks', id, { title: task.title, type: task.type });
    eventBus.emit('task.created', 'task', id, { title: task.title, type: task.type });
    get().loadTasks();
    return task;
  },

  updateTask: (id, data) => {
    const db = getDatabase();
    const fields: string[] = [];
    const values: unknown[] = [];

    const fieldMap: Record<string, string> = {
      title: 'title',
      description: 'description',
      type: 'type',
      priority: 'priority',
      dueAt: 'due_at',
      linkedEntityType: 'linked_entity_type',
      linkedEntityId: 'linked_entity_id',
      assignedTo: 'assigned_to',
      status: 'status',
    };

    for (const [key, val] of Object.entries(data)) {
      const col = fieldMap[key];
      if (col) { fields.push(`${col} = ?`); values.push(val ?? null); }
    }

    if (fields.length === 0) return;

    values.push(id);
    db.run(`UPDATE tasks SET ${fields.join(', ')} WHERE id = ?`, values);
    saveDatabase();
    trackUpdate('tasks', id, data as unknown as Record<string, unknown>);
    get().loadTasks();
  },

  completeTask: (id) => {
    const db = getDatabase();
    const now = new Date().toISOString();
    db.run(
      `UPDATE tasks SET status = 'completed', completed_at = ? WHERE id = ?`,
      [now, id]
    );
    saveDatabase();
    trackUpdate('tasks', id, { status: 'completed' });
    eventBus.emit('task.completed', 'task', id, {});
    get().loadTasks();
  },

  deleteTask: (id) => {
    const db = getDatabase();
    db.run('DELETE FROM tasks WHERE id = ?', [id]);
    saveDatabase();
    trackDelete('tasks', id);
    get().loadTasks();
  },

  getTasksForEntity: (entityType, entityId) => {
    return get().tasks.filter(
      t => t.linkedEntityType === entityType && t.linkedEntityId === entityId
    );
  },
}));
